# Generated by Django 5.0.3 on 2024-04-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeDateTime', models.DateTimeField()),
                ('stockName', models.CharField(max_length=100)),
                ('listingPrice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('pricePerUnit', models.IntegerField()),
            ],
        ),
    ]
