# Generated by Django 5.0.3 on 2024-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('stockName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('listingPrice', models.IntegerField()),
            ],
        ),
    ]
