# Generated by Django 5.0.3 on 2024-04-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(default='confirmed', max_length=100),
        ),
    ]
